### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by regalstreak** [CyanogenMod/android_device_oneplus_oneplus2#9]

**Comment by Martinusbe** [comment]
what is zenhub?

**Comment by anthraxx** [comment]
I hope its not dead... still awaiting a release for oneplus2 :smile:

**Comment by regalstreak** [comment]
@martinusbe its some collab extension for chrome. Just tried it.

**Comment by xdevs23** [comment]
lol

**Comment by xdevs23** [comment]
No it is not dead I am trying to help you on fingerprint stuff

**Comment by regalstreak** [comment]
@xdevs23  lulz

**Comment by xdevs23** [comment]
Ok I think those files could be improved in kernel source:

In drivers/input/misc:

fpc1020_capture.c
fpc1020_capture.h
fpc1020_common.c
fpc1020_common.h
fpc1020.h
fpc1020_input.h
fpc1020_main.c
fpc1020_nav.c
fpc1020_regs.h
fpc1020_regulator.c
fpc1020_regulator.h

**Comment by regalstreak** [comment]
Was alive again. Closing #9
